/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ThongKe;

import Connect.Connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultCaret;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.BarRenderer3D;
import org.jfree.chart.renderer.category.DefaultCategoryItemRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;
public class thongke extends javax.swing.JPanel {

   Connect hd = new Connect();
    Connection con = hd.getConnect();
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    NumberFormat chuyentien = new DecimalFormat("###,###,###");
    SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy HH:mm a");
    public thongke() {
        initComponents();
         load2();
        load1();
        ban();
        tienmon();
        mon();
        loai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbaleHD = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmon = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        dateChooser1 = new datechooser.beans.DateChooserCombo();
        jLabel13 = new javax.swing.JLabel();
        dateChooser2 = new datechooser.beans.DateChooserCombo();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbltongloai = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbltongsomondaban = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbltongmon = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbltongsoban = new javax.swing.JLabel();
        btndoanhthungay = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbltienthu = new javax.swing.JLabel();
        lbltienmon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblhd = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        tbaleHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Thời gian", "Tiền món", "Số bán", "Các món"
            }
        ));
        jScrollPane2.setViewportView(tbaleHD);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("Thống kê theo hóa đơn");

        tbmon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên món", "Đơn vị tính", "Số lượng", "Doanh thu"
            }
        ));
        jScrollPane1.setViewportView(tbmon);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Đến ngày");

        dateChooser1.setCurrentView(new datechooser.view.appearance.AppearancesList("custom",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 11),
                    new java.awt.Color(0, 51, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooser1.setCalendarBackground(new java.awt.Color(133, 140, 148));
    dateChooser1.setLocale(new java.util.Locale("vi", "VN", ""));
    dateChooser1.setNavigateFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11));
    dateChooser1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_PERIOD);

    jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel13.setText("Từ ngày");

    dateChooser2.setCurrentView(new datechooser.view.appearance.AppearancesList("custom",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 11),
                new java.awt.Color(0, 51, 255),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
dateChooser2.setCalendarBackground(new java.awt.Color(133, 140, 148));
dateChooser2.setLocale(new java.util.Locale("vi", "VN", ""));
dateChooser2.setNavigateFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11));
dateChooser2.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_PERIOD);

jButton1.setText("Thống kê");
jButton1.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
    }
    });

    jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(172, 0, 5));
    jLabel11.setText("Thống kê theo món");

    jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel8.setText("Tổng số loại:");

    lbltongloai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lbltongloai.setForeground(new java.awt.Color(17, 131, 40));
    lbltongloai.setText(".........");

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel2.setText("Tổng số món đã bán:");

    lbltongsomondaban.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbltongsomondaban.setForeground(new java.awt.Color(17, 131, 40));
    lbltongsomondaban.setText("........");

    jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton4.setText("Thống kê doanh thu trong năm");

    jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton3.setText("Thống kê doanh thu trong tháng");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    lbltongmon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lbltongmon.setForeground(new java.awt.Color(17, 131, 40));
    lbltongmon.setText("........");

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel7.setText("Tổng số món:");

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel6.setText("Tổng số bàn: ");

    lbltongsoban.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lbltongsoban.setForeground(new java.awt.Color(17, 131, 40));
    lbltongsoban.setText(".......");

    btndoanhthungay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btndoanhthungay.setText("Thống kê doanh thu trong ngày");
    btndoanhthungay.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btndoanhthungayActionPerformed(evt);
        }
    });

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel3.setText("Tiền thu về:");

    lbltienthu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lbltienthu.setForeground(new java.awt.Color(162, 11, 11));
    lbltienthu.setText(".....");

    lbltienmon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lbltienmon.setForeground(new java.awt.Color(162, 11, 11));
    lbltienmon.setText("....");

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel5.setText("Tiền món:");

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setText("Tổng số hóa đơn thanh toán:");

    lblhd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lblhd.setForeground(new java.awt.Color(82, 15, 172));
    lblhd.setText(".....");

    jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel1)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lbltienmon, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbltienthu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblhd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(lbltongsomondaban)
                    .addGap(55, 55, 55))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbltongsoban)
                    .addGap(37, 37, 37)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbltongmon)
                    .addGap(37, 37, 37)
                    .addComponent(jLabel8)
                    .addGap(31, 31, 31)
                    .addComponent(lbltongloai)))
            .addGap(283, 283, 283))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btndoanhthungay)
                            .addGap(361, 361, 361))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(59, 59, 59)))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(186, 186, 186))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel13)
                    .addGap(18, 18, 18)
                    .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(jLabel14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(dateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(397, 397, 397))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 721, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(dateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
            .addComponent(jLabel11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblhd))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(lbltienmon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(16, 16, 16)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lbltienthu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbltongsomondaban))
                    .addGap(56, 56, 56)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)
                        .addComponent(lbltongloai)
                        .addComponent(lbltongsoban)
                        .addComponent(lbltongmon))))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btndoanhthungay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(16, 16, 16))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE)))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (dateChooser1.getText().isEmpty() || dateChooser2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn ngày để thống kê ");
            return;
        }
        loadtimkiem1();
        loadtimkiem2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btndoanhthungayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoanhthungayActionPerformed
        try {
            String a = "Select GioDen ,SoLuong* Gia as TienMon "
            + "From chitiethd AS ct  INNER JOIN hoadon AS hd ON hd.MaHoaDon = ct.MaHoaDon";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(Connect.getConnect(), a);
            JFreeChart chart = ChartFactory.createBarChart3D("Thống Kê Doanh Thu Theo Ngày", "Thời gian", "Tiền", dataset, PlotOrientation.VERTICAL, true, true, true);                    
            ChartFrame frame = new ChartFrame("Bảng thống kê", chart);
            frame.setSize(700, 600);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btndoanhthungayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndoanhthungay;
    private datechooser.beans.DateChooserCombo dateChooser1;
    private datechooser.beans.DateChooserCombo dateChooser2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblhd;
    private javax.swing.JLabel lbltienmon;
    private javax.swing.JLabel lbltienthu;
    private javax.swing.JLabel lbltongloai;
    private javax.swing.JLabel lbltongmon;
    private javax.swing.JLabel lbltongsoban;
    private javax.swing.JLabel lbltongsomondaban;
    private javax.swing.JTable tbaleHD;
    private javax.swing.JTable tbmon;
    // End of variables declaration//GEN-END:variables
  public void load1() {   // thống kê theo hóa đơn
        model = (DefaultTableModel) tbaleHD.getModel();
        model.setRowCount(0);
        try {
            String a = "Select ct.MaHoaDon,GioDen , SoLuong* Gia as TienMon, MaBan ,TenMon "
                    + "From chitiethd AS ct  INNER JOIN hoadon AS hd ON hd.MaHoaDon = ct.MaHoaDon";
            st = con.createStatement();
            rs = st.executeQuery(a);
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(chuyentien.format(rs.getInt(3)));
                row.add(rs.getInt(4));
                row.add(rs.getString(5));
                model.addRow(row);
            }
            tbaleHD.setModel(model);
        } catch (Exception e) {
            System.out.println("lỗi hệ thống");
        }

    }

   
    public void load2() {   // thống kê theo món
        try {
            model = (DefaultTableModel) tbmon.getModel();
            model.setRowCount(0);
            String a = "Select TenMon, DVT, SoLuong, Gia*SoLuong as thanhtien "
                    + " From chitiethd ";
            st = con.createStatement();
            rs = st.executeQuery(a);
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(chuyentien.format(rs.getInt(4)));
                model.addRow(row);
            }
            tbmon.setModel(model);
        } catch (Exception ex) {
            System.out.println("lỗi hệ thống");
        }

    }

    public void tienmon() {
        try {
            String a = "select COUNT (SoLuong* Gia)as tongtien ,sum (Gia*SoLuong)as tienmon, "
                    + " sum (Gia*SoLuong) as thuve ,sum(SoLuong) as soluongmon from chitiethd;";
            PreparedStatement ps = con.prepareStatement(a);
            rs = ps.executeQuery();
            while (rs.next()) {
                lblhd.setText(rs.getString("tongtien")); // tổng số hóa đơn đã thanh toán
                lbltienmon.setText(chuyentien.format(rs.getInt("tienmon")) + " VND");//  tổng tiền món           
                lbltienthu.setText(chuyentien.format(rs.getInt("thuve")) + " VND");// tổng tiền thu về 
                lbltongsomondaban.setText(rs.getString("soluongmon"));//  tổng số món đã bán
            }
        } catch (Exception e) {
            System.out.println("lỗi hệ thống");
        }
    }

    public void ban() {
        try {
            String a = "select count(MaBan)as maban FROM ban";
            PreparedStatement ps = con.prepareStatement(a);
            rs = ps.executeQuery();
            while (rs.next()) {
                lbltongsoban.setText(rs.getString("maban")); //tổng số bàn đã bán
            }
        } catch (Exception ex) {
            System.out.println("lỗi hệ thống");
        }

    }

    public void mon() {
        try {
            String a = "select count (TenMon)as mon FROM thucdon ";
            PreparedStatement ps = con.prepareStatement(a);
            rs = ps.executeQuery();
            while (rs.next()) {
                lbltongmon.setText(rs.getString("mon")); // tổng số món đã bán
            }
        } catch (Exception ex) {
            System.out.println("lỗi hệ thống");
        }
    }

    public void loai() {
        try {
            String a = " select count (TenLoai)as loai FROM nhommon";
            PreparedStatement ps = con.prepareStatement(a);
            rs = ps.executeQuery();
            while (rs.next()) {
                lbltongloai.setText(rs.getString("loai")); // tổng số loại đã bán
            }
        } catch (Exception ex) {
            System.out.println("lỗi hệ thống");
        }
    }

    public void loadtimkiem2() { // tìm kiếm theo món

        try {
            Date d1 = dateChooser1.getSelectedDate().getTime();
            Date d2 = dateChooser2.getSelectedDate().getTime();
            String s1 = String.format("%1$tY-%1$tm-%1$td", d1);
            String s2 = String.format("%1$tY-%1$tm-%1$td", d2);
            model = (DefaultTableModel) tbmon.getModel();
            model.setRowCount(0);
            String a = "Select TenMon, DVT, SoLuong, Gia*SoLuong as thanhtien,GioDen "
                    + " From chitiethd AS ct  INNER JOIN hoadon AS hd ON hd.MaHoaDon = ct.MaHoaDon where GioDen  BETWEEN '" + s1 + "' AND '" + s2 + "'";
            rs = st.executeQuery(a);
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(chuyentien.format(rs.getInt(4)));
                model.addRow(row);
            }
            tbmon.setModel(model);
             
      
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void loadtimkiem1() { // tìm kiếm theo hóa đơn

        try {
            Date d1 = dateChooser1.getSelectedDate().getTime();
            Date d2 = dateChooser2.getSelectedDate().getTime();
            String s1 = String.format("%1$tY-%1$tm-%1$td", d1);
            String s2 = String.format("%1$tY-%1$tm-%1$td", d2);
            model = (DefaultTableModel) tbaleHD.getModel();
            model.setRowCount(0);
            String a = "Select ct.MaHoaDon,GioDen , SoLuong* Gia as TienMon, MaBan ,TenMon "
                    + "From chitiethd AS ct  INNER JOIN hoadon AS hd ON hd.MaHoaDon = ct.MaHoaDon where GioDen  BETWEEN '" + s1 + "' AND '" + s2 + "'";
            st = con.createStatement();
            rs = st.executeQuery(a);
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(sf.format(rs.getObject(2)));
                row.add(chuyentien.format(rs.getInt(3)));
                row.add(rs.getInt(4));
                row.add(rs.getString(5));
                model.addRow(row);
            }
            tbaleHD.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
